[network]
name = "testnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "your testnet mnemonic here"
balance = 100000000

[contracts.bitstack]
path = "contracts/bitstack.clar"
clarity_version = 2

[settings]
batching = true
epoch = "2.4"
